; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-vectorize | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128-ni:1-p2:32:8:8:32-ni:2"
target triple = "x86_64-unknown-linux-gnu"

; Make sure this does not crash when trying to clean up LCSSA phi nodes
; inserted when generating bounds checks which are later discarded.

define void @test(i1 %c, ptr %p, i32 %arg) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: i1 [[C:%.*]], ptr [[P:%.*]], i32 [[ARG:%.*]]) {
; CHECK-NEXT:  [[BB:.*]]:
; CHECK-NEXT:    br label %[[LOOP3_PREHEADER:.*]]
; CHECK:       [[UNREACHABLE:.*]]:
; CHECK-NEXT:    [[SELECT:%.*]] = select i1 false, i32 0, i32 8
; CHECK-NEXT:    [[ZEXT:%.*]] = zext i32 [[SELECT]] to i64
; CHECK-NEXT:    br label %[[LOOP3_PREHEADER]]
; CHECK:       [[LOOP3_PREHEADER]]:
; CHECK-NEXT:    [[PHI_PH:%.*]] = phi i64 [ 1, %[[BB]] ], [ [[ZEXT]], %[[UNREACHABLE]] ]
; CHECK-NEXT:    br label %[[LOOP3:.*]]
; CHECK:       [[LOOP3]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ 0, %[[LOOP3]] ], [ [[PHI_PH]], %[[LOOP3_PREHEADER]] ]
; CHECK-NEXT:    br i1 false, label %[[PICK_LOOP:.*]], label %[[LOOP3]]
; CHECK:       [[PICK_LOOP]]:
; CHECK-NEXT:    [[PHI_LCSSA:%.*]] = phi i64 [ [[PHI]], %[[LOOP3]] ]
; CHECK-NEXT:    br i1 [[C]], label %[[LOOP_PREHEADER:.*]], label %[[LOOP2_PREHEADER:.*]]
; CHECK:       [[LOOP_PREHEADER]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[PHI5:%.*]] = phi i64 [ [[ADD7:%.*]], %[[LOOP]] ], [ 0, %[[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[PHI6:%.*]] = phi i32 [ [[ADD:%.*]], %[[LOOP]] ], [ [[ARG]], %[[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[ADD]] = add i32 [[PHI6]], 1
; CHECK-NEXT:    [[ADD7]] = add i64 [[PHI5]], 1
; CHECK-NEXT:    [[SHL:%.*]] = shl i32 [[PHI6]], 1
; CHECK-NEXT:    [[ZEXT8:%.*]] = zext i32 [[SHL]] to i64
; CHECK-NEXT:    [[GETELEMENTPTR:%.*]] = getelementptr i8, ptr [[P]], i64 [[ZEXT8]]
; CHECK-NEXT:    store i16 0, ptr [[GETELEMENTPTR]], align 2
; CHECK-NEXT:    [[ICMP:%.*]] = icmp ult i64 [[PHI5]], [[PHI_LCSSA]]
; CHECK-NEXT:    br i1 [[ICMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[LOOP2_PREHEADER]]:
; CHECK-NEXT:    br i1 false, label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_RND_UP:%.*]] = add i64 [[PHI]], 15
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N_RND_UP]], 16
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N_RND_UP]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TRIP_COUNT_MINUS_1:%.*]] = sub i64 [[PHI]], 1
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <16 x i64> poison, i64 [[TRIP_COUNT_MINUS_1]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <16 x i64> [[BROADCAST_SPLATINSERT]], <16 x i64> poison, <16 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_STORE_CONTINUE30:.*]] ]
; CHECK-NEXT:    [[VEC_IND:%.*]] = phi <16 x i64> [ <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7, i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>, %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[PRED_STORE_CONTINUE30]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ule <16 x i64> [[VEC_IND]], [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <16 x i1> [[TMP0]], i32 0
; CHECK-NEXT:    br i1 [[TMP1]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_CONTINUE:.*]]
; CHECK:       [[PRED_STORE_IF]]:
; CHECK-NEXT:    [[TMP2:%.*]] = add i64 [[INDEX]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP2]]
; CHECK-NEXT:    store i8 0, ptr [[TMP3]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE]]
; CHECK:       [[PRED_STORE_CONTINUE]]:
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <16 x i1> [[TMP0]], i32 1
; CHECK-NEXT:    br i1 [[TMP4]], label %[[PRED_STORE_IF1:.*]], label %[[PRED_STORE_CONTINUE2:.*]]
; CHECK:       [[PRED_STORE_IF1]]:
; CHECK-NEXT:    [[TMP5:%.*]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP5]]
; CHECK-NEXT:    store i8 0, ptr [[TMP6]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE2]]
; CHECK:       [[PRED_STORE_CONTINUE2]]:
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <16 x i1> [[TMP0]], i32 2
; CHECK-NEXT:    br i1 [[TMP7]], label %[[PRED_STORE_IF3:.*]], label %[[PRED_STORE_CONTINUE4:.*]]
; CHECK:       [[PRED_STORE_IF3]]:
; CHECK-NEXT:    [[TMP8:%.*]] = add i64 [[INDEX]], 2
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP8]]
; CHECK-NEXT:    store i8 0, ptr [[TMP9]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE4]]
; CHECK:       [[PRED_STORE_CONTINUE4]]:
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <16 x i1> [[TMP0]], i32 3
; CHECK-NEXT:    br i1 [[TMP10]], label %[[PRED_STORE_IF5:.*]], label %[[PRED_STORE_CONTINUE6:.*]]
; CHECK:       [[PRED_STORE_IF5]]:
; CHECK-NEXT:    [[TMP11:%.*]] = add i64 [[INDEX]], 3
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP11]]
; CHECK-NEXT:    store i8 0, ptr [[TMP12]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE6]]
; CHECK:       [[PRED_STORE_CONTINUE6]]:
; CHECK-NEXT:    [[TMP13:%.*]] = extractelement <16 x i1> [[TMP0]], i32 4
; CHECK-NEXT:    br i1 [[TMP13]], label %[[PRED_STORE_IF7:.*]], label %[[PRED_STORE_CONTINUE8:.*]]
; CHECK:       [[PRED_STORE_IF7]]:
; CHECK-NEXT:    [[TMP14:%.*]] = add i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP14]]
; CHECK-NEXT:    store i8 0, ptr [[TMP15]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE8]]
; CHECK:       [[PRED_STORE_CONTINUE8]]:
; CHECK-NEXT:    [[TMP16:%.*]] = extractelement <16 x i1> [[TMP0]], i32 5
; CHECK-NEXT:    br i1 [[TMP16]], label %[[PRED_STORE_IF9:.*]], label %[[PRED_STORE_CONTINUE10:.*]]
; CHECK:       [[PRED_STORE_IF9]]:
; CHECK-NEXT:    [[TMP17:%.*]] = add i64 [[INDEX]], 5
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP17]]
; CHECK-NEXT:    store i8 0, ptr [[TMP18]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE10]]
; CHECK:       [[PRED_STORE_CONTINUE10]]:
; CHECK-NEXT:    [[TMP19:%.*]] = extractelement <16 x i1> [[TMP0]], i32 6
; CHECK-NEXT:    br i1 [[TMP19]], label %[[PRED_STORE_IF11:.*]], label %[[PRED_STORE_CONTINUE12:.*]]
; CHECK:       [[PRED_STORE_IF11]]:
; CHECK-NEXT:    [[TMP20:%.*]] = add i64 [[INDEX]], 6
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP20]]
; CHECK-NEXT:    store i8 0, ptr [[TMP21]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE12]]
; CHECK:       [[PRED_STORE_CONTINUE12]]:
; CHECK-NEXT:    [[TMP22:%.*]] = extractelement <16 x i1> [[TMP0]], i32 7
; CHECK-NEXT:    br i1 [[TMP22]], label %[[PRED_STORE_IF13:.*]], label %[[PRED_STORE_CONTINUE14:.*]]
; CHECK:       [[PRED_STORE_IF13]]:
; CHECK-NEXT:    [[TMP23:%.*]] = add i64 [[INDEX]], 7
; CHECK-NEXT:    [[TMP24:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP23]]
; CHECK-NEXT:    store i8 0, ptr [[TMP24]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE14]]
; CHECK:       [[PRED_STORE_CONTINUE14]]:
; CHECK-NEXT:    [[TMP25:%.*]] = extractelement <16 x i1> [[TMP0]], i32 8
; CHECK-NEXT:    br i1 [[TMP25]], label %[[PRED_STORE_IF15:.*]], label %[[PRED_STORE_CONTINUE16:.*]]
; CHECK:       [[PRED_STORE_IF15]]:
; CHECK-NEXT:    [[TMP26:%.*]] = add i64 [[INDEX]], 8
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP26]]
; CHECK-NEXT:    store i8 0, ptr [[TMP27]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE16]]
; CHECK:       [[PRED_STORE_CONTINUE16]]:
; CHECK-NEXT:    [[TMP28:%.*]] = extractelement <16 x i1> [[TMP0]], i32 9
; CHECK-NEXT:    br i1 [[TMP28]], label %[[PRED_STORE_IF17:.*]], label %[[PRED_STORE_CONTINUE18:.*]]
; CHECK:       [[PRED_STORE_IF17]]:
; CHECK-NEXT:    [[TMP29:%.*]] = add i64 [[INDEX]], 9
; CHECK-NEXT:    [[TMP30:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP29]]
; CHECK-NEXT:    store i8 0, ptr [[TMP30]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE18]]
; CHECK:       [[PRED_STORE_CONTINUE18]]:
; CHECK-NEXT:    [[TMP31:%.*]] = extractelement <16 x i1> [[TMP0]], i32 10
; CHECK-NEXT:    br i1 [[TMP31]], label %[[PRED_STORE_IF19:.*]], label %[[PRED_STORE_CONTINUE20:.*]]
; CHECK:       [[PRED_STORE_IF19]]:
; CHECK-NEXT:    [[TMP32:%.*]] = add i64 [[INDEX]], 10
; CHECK-NEXT:    [[TMP33:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP32]]
; CHECK-NEXT:    store i8 0, ptr [[TMP33]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE20]]
; CHECK:       [[PRED_STORE_CONTINUE20]]:
; CHECK-NEXT:    [[TMP34:%.*]] = extractelement <16 x i1> [[TMP0]], i32 11
; CHECK-NEXT:    br i1 [[TMP34]], label %[[PRED_STORE_IF21:.*]], label %[[PRED_STORE_CONTINUE22:.*]]
; CHECK:       [[PRED_STORE_IF21]]:
; CHECK-NEXT:    [[TMP35:%.*]] = add i64 [[INDEX]], 11
; CHECK-NEXT:    [[TMP36:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP35]]
; CHECK-NEXT:    store i8 0, ptr [[TMP36]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE22]]
; CHECK:       [[PRED_STORE_CONTINUE22]]:
; CHECK-NEXT:    [[TMP37:%.*]] = extractelement <16 x i1> [[TMP0]], i32 12
; CHECK-NEXT:    br i1 [[TMP37]], label %[[PRED_STORE_IF23:.*]], label %[[PRED_STORE_CONTINUE24:.*]]
; CHECK:       [[PRED_STORE_IF23]]:
; CHECK-NEXT:    [[TMP38:%.*]] = add i64 [[INDEX]], 12
; CHECK-NEXT:    [[TMP39:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP38]]
; CHECK-NEXT:    store i8 0, ptr [[TMP39]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE24]]
; CHECK:       [[PRED_STORE_CONTINUE24]]:
; CHECK-NEXT:    [[TMP40:%.*]] = extractelement <16 x i1> [[TMP0]], i32 13
; CHECK-NEXT:    br i1 [[TMP40]], label %[[PRED_STORE_IF25:.*]], label %[[PRED_STORE_CONTINUE26:.*]]
; CHECK:       [[PRED_STORE_IF25]]:
; CHECK-NEXT:    [[TMP41:%.*]] = add i64 [[INDEX]], 13
; CHECK-NEXT:    [[TMP42:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP41]]
; CHECK-NEXT:    store i8 0, ptr [[TMP42]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE26]]
; CHECK:       [[PRED_STORE_CONTINUE26]]:
; CHECK-NEXT:    [[TMP43:%.*]] = extractelement <16 x i1> [[TMP0]], i32 14
; CHECK-NEXT:    br i1 [[TMP43]], label %[[PRED_STORE_IF27:.*]], label %[[PRED_STORE_CONTINUE28:.*]]
; CHECK:       [[PRED_STORE_IF27]]:
; CHECK-NEXT:    [[TMP44:%.*]] = add i64 [[INDEX]], 14
; CHECK-NEXT:    [[TMP45:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP44]]
; CHECK-NEXT:    store i8 0, ptr [[TMP45]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE28]]
; CHECK:       [[PRED_STORE_CONTINUE28]]:
; CHECK-NEXT:    [[TMP46:%.*]] = extractelement <16 x i1> [[TMP0]], i32 15
; CHECK-NEXT:    br i1 [[TMP46]], label %[[PRED_STORE_IF29:.*]], label %[[PRED_STORE_CONTINUE30]]
; CHECK:       [[PRED_STORE_IF29]]:
; CHECK-NEXT:    [[TMP47:%.*]] = add i64 [[INDEX]], 15
; CHECK-NEXT:    [[TMP48:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP47]]
; CHECK-NEXT:    store i8 0, ptr [[TMP48]], align 1
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE30]]
; CHECK:       [[PRED_STORE_CONTINUE30]]:
; CHECK-NEXT:    [[VEC_IND_NEXT]] = add <16 x i64> [[VEC_IND]], splat (i64 16)
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 16
; CHECK-NEXT:    br i1 true, label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br i1 true, label %[[EXIT2:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[LOOP2_PREHEADER]] ]
; CHECK-NEXT:    br label %[[LOOP2:.*]]
; CHECK:       [[LOOP2]]:
; CHECK-NEXT:    [[PHI10:%.*]] = phi i64 [ [[ADD12:%.*]], %[[LOOP2]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; CHECK-NEXT:    [[GETELEMENTPTR11:%.*]] = getelementptr i8, ptr [[P]], i64 [[PHI10]]
; CHECK-NEXT:    store i8 0, ptr [[GETELEMENTPTR11]], align 1
; CHECK-NEXT:    [[ADD12]] = add i64 [[PHI10]], 1
; CHECK-NEXT:    [[ICMP13:%.*]] = icmp ult i64 [[ADD12]], [[PHI_LCSSA]]
; CHECK-NEXT:    br i1 [[ICMP13]], label %[[LOOP2]], label %[[EXIT2]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
; CHECK:       [[EXIT2]]:
; CHECK-NEXT:    ret void
;
bb:
  br label %loop3.preheader

unreachable:
  %select = select i1 false, i32 0, i32 8
  %zext = zext i32 %select to i64
  br label %loop3.preheader

loop3.preheader:
  %phi.ph = phi i64 [ 1, %bb ], [ %zext, %unreachable ]
  br label %loop3

loop3:
  %phi = phi i64 [ 0, %loop3 ], [ %phi.ph, %loop3.preheader ]
  br i1 false, label %pick.loop, label %loop3

pick.loop:
  %phi.lcssa = phi i64 [ %phi, %loop3 ]
  br i1 %c, label %loop.preheader, label %loop2.preheader

loop.preheader:
  br label %loop

loop:
  %phi5 = phi i64 [ %add7, %loop ], [ 0, %loop.preheader ]
  %phi6 = phi i32 [ %add, %loop ], [ %arg, %loop.preheader ]
  %add = add i32 %phi6, 1
  %add7 = add i64 %phi5, 1
  %shl = shl i32 %phi6, 1
  %zext8 = zext i32 %shl to i64
  %getelementptr = getelementptr i8, ptr %p, i64 %zext8
  store i16 0, ptr %getelementptr, align 2
  %icmp = icmp ult i64 %phi5, %phi.lcssa
  br i1 %icmp, label %loop, label %exit

loop2.preheader:
  br label %loop2

loop2:
  %phi10 = phi i64 [ %add12, %loop2 ], [ 0, %loop2.preheader ]
  %getelementptr11 = getelementptr i8, ptr %p, i64 %phi10
  store i8 0, ptr %getelementptr11, align 1
  %add12 = add i64 %phi10, 1
  %icmp13 = icmp ult i64 %add12, %phi.lcssa
  br i1 %icmp13, label %loop2, label %exit2

exit:
  ret void

exit2:
  ret void
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
;.
