; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=sccp -S | FileCheck %s

define ptr @scalable_vector_getelementptr(i64 %x) {
; CHECK-LABEL: @scalable_vector_getelementptr(
; CHECK-NEXT:    ret ptr poison
;
  %ptr = getelementptr <vscale x 4 x i32>, ptr null, i64 1
  ret ptr %ptr
}
