; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=riscv32 --expand-ir-insts < %s | FileCheck %s

define i96 @fptosi_fp128_i96(fp128 %arg) {
; CHECK-LABEL: define i96 @fptosi_fp128_i96(
; CHECK-SAME: fp128 [[ARG:%.*]]) {
; CHECK-NEXT:  [[FP_TO_I_ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast fp128 [[ARG]] to i128
; CHECK-NEXT:    [[TMP1:%.*]] = icmp sgt i128 [[TMP0]], -1
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], i96 1, i96 -1
; CHECK-NEXT:    [[TMP3:%.*]] = lshr i128 [[TMP0]], 112
; CHECK-NEXT:    [[TMP4:%.*]] = and i128 [[TMP3]], 32767
; CHECK-NEXT:    [[TMP5:%.*]] = and i128 [[TMP0]], 5192296858534827628530496329220095
; CHECK-NEXT:    [[TMP6:%.*]] = or i128 [[TMP5]], 5192296858534827628530496329220096
; CHECK-NEXT:    [[TMP7:%.*]] = icmp ult i128 [[TMP4]], 16383
; CHECK-NEXT:    br i1 [[TMP7]], label %[[FP_TO_I_CLEANUP:.*]], label %[[FP_TO_I_IF_END:.*]]
; CHECK:       [[FP_TO_I_IF_END]]:
; CHECK-NEXT:    [[TMP8:%.*]] = add i128 [[TMP4]], -16479
; CHECK-NEXT:    [[TMP9:%.*]] = icmp ult i128 [[TMP8]], -96
; CHECK-NEXT:    br i1 [[TMP9]], label %[[FP_TO_I_IF_THEN5:.*]], label %[[FP_TO_I_IF_END9:.*]]
; CHECK:       [[FP_TO_I_IF_THEN5]]:
; CHECK-NEXT:    [[TMP10:%.*]] = select i1 [[TMP1]], i96 39614081257132168796771975167, i96 -39614081257132168796771975168
; CHECK-NEXT:    br label %[[FP_TO_I_CLEANUP]]
; CHECK:       [[FP_TO_I_IF_END9]]:
; CHECK-NEXT:    [[TMP11:%.*]] = icmp ult i128 [[TMP4]], 16495
; CHECK-NEXT:    br i1 [[TMP11]], label %[[FP_TO_I_IF_THEN12:.*]], label %[[FP_TO_I_IF_ELSE:.*]]
; CHECK:       [[FP_TO_I_IF_THEN12]]:
; CHECK-NEXT:    [[TMP12:%.*]] = sub i128 16495, [[TMP4]]
; CHECK-NEXT:    [[TMP13:%.*]] = lshr i128 [[TMP6]], [[TMP12]]
; CHECK-NEXT:    [[TMP14:%.*]] = trunc i128 [[TMP13]] to i96
; CHECK-NEXT:    [[TMP15:%.*]] = mul i96 [[TMP14]], [[TMP2]]
; CHECK-NEXT:    br label %[[FP_TO_I_CLEANUP]]
; CHECK:       [[FP_TO_I_IF_ELSE]]:
; CHECK-NEXT:    [[TMP16:%.*]] = add i128 [[TMP4]], -16495
; CHECK-NEXT:    [[TMP17:%.*]] = trunc i128 [[TMP6]] to i96
; CHECK-NEXT:    [[TMP18:%.*]] = trunc i128 [[TMP16]] to i96
; CHECK-NEXT:    [[TMP19:%.*]] = shl i96 [[TMP17]], [[TMP18]]
; CHECK-NEXT:    [[TMP20:%.*]] = mul i96 [[TMP19]], [[TMP2]]
; CHECK-NEXT:    br label %[[FP_TO_I_CLEANUP]]
; CHECK:       [[FP_TO_I_CLEANUP]]:
; CHECK-NEXT:    [[TMP21:%.*]] = phi i96 [ [[TMP10]], %[[FP_TO_I_IF_THEN5]] ], [ [[TMP15]], %[[FP_TO_I_IF_THEN12]] ], [ [[TMP20]], %[[FP_TO_I_IF_ELSE]] ], [ 0, %[[FP_TO_I_ENTRY]] ]
; CHECK-NEXT:    ret i96 [[TMP21]]
;
  %res = fptosi fp128 %arg to i96
  ret i96 %res
}
