; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-attributes --version 6
; RUN: opt < %s -passes=function-attrs -S | FileCheck %s
; PR2792

@g = global i32 0		; <ptr> [#uses=1]

define i32 @f() {
; CHECK: Function Attrs: nofree norecurse nosync nounwind memory(read, argmem: none, inaccessiblemem: readwrite, target_mem: none)
; CHECK-LABEL: define i32 @f(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[T:%.*]] = load volatile i32, ptr @g, align 4
; CHECK-NEXT:    ret i32 [[T]]
;
  %t = load volatile i32, ptr @g		; <i32> [#uses=1]
  ret i32 %t
}
