; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define ptr @f1(ptr %arg, i64 %arg1) {
; CHECK-LABEL: @f1(
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [6 x i32], ptr [[TMP1:%.*]], i64 0, i64 [[ARG1:%.*]]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP2]], i64 72
; CHECK-NEXT:    ret ptr [[TMP3]]
;
  %1 = getelementptr [6 x i32], ptr %arg, i64 3
  %2 = getelementptr [6 x i32], ptr %1, i64 0, i64 %arg1
  ret ptr %2
}

define ptr @f2(ptr %arg, i64 %arg1) {
; CHECK-LABEL: @f2(
; CHECK-NEXT:    [[DOTSPLIT:%.*]] = getelementptr [6 x i32], ptr [[TMP1:%.*]], i64 [[ARG1:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [6 x i32], ptr [[DOTSPLIT]], i64 0, i64 [[ARG1]]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP2]], i64 72
; CHECK-NEXT:    ret ptr [[TMP3]]
;
  %1 = getelementptr [6 x i32], ptr %arg, i64 3
  %2 = getelementptr [6 x i32], ptr %1, i64 %arg1, i64 %arg1
  ret ptr %2
}
