; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt < %s -passes=infer-alignment -S | FileCheck %s

define void @test_assume_base_variable_gep(ptr %base, i64 %idx) {
; CHECK-LABEL: define void @test_assume_base_variable_gep
; CHECK-SAME: (ptr [[BASE:%.*]], i64 [[IDX:%.*]]) {
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[BASE]], i64 16) ]
; CHECK-NEXT:    [[IDX8:%.*]] = shl i64 [[IDX]], 1
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds float, ptr [[BASE]], i64 [[IDX8]]
; CHECK-NEXT:    [[LOAD:%.*]] = load float, ptr [[GEP]], align 8
; CHECK-NEXT:    store float [[LOAD]], ptr [[GEP]], align 8
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "align"(ptr %base, i64 16) ]
  %idx8 = shl i64 %idx, 1
  %gep = getelementptr inbounds float, ptr %base, i64 %idx8
  %load = load float, ptr %gep, align 4
  store float %load, ptr %gep, align 4
  ret void
}

define void @test_multiple_geps(ptr %base, i64 %i, i64 %j) {
; CHECK-LABEL: define void @test_multiple_geps
; CHECK-SAME: (ptr [[BASE:%.*]], i64 [[I:%.*]], i64 [[J:%.*]]) {
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[BASE]], i64 16) ]
; CHECK-NEXT:    [[I_SHIFTED:%.*]] = shl i64 [[I]], 2
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds float, ptr [[BASE]], i64 [[I_SHIFTED]]
; CHECK-NEXT:    [[J_SHIFTED:%.*]] = shl i64 [[J]], 1
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds float, ptr [[GEP1]], i64 [[J_SHIFTED]]
; CHECK-NEXT:    [[LOAD:%.*]] = load float, ptr [[GEP2]], align 8
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "align"(ptr %base, i64 16) ]
  %i.shifted = shl i64 %i, 2
  %gep1 = getelementptr inbounds float, ptr %base, i64 %i.shifted
  %j.shifted = shl i64 %j, 1
  %gep2 = getelementptr inbounds float, ptr %gep1, i64 %j.shifted
  %load = load float, ptr %gep2, align 4
  ret void
}

define void @test_constant_and_variable_offset(ptr %base, i64 %idx) {
; CHECK-LABEL: define void @test_constant_and_variable_offset
; CHECK-SAME: (ptr [[BASE:%.*]], i64 [[IDX:%.*]]) {
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[BASE]], i64 16) ]
; CHECK-NEXT:    [[GEP_CONST:%.*]] = getelementptr inbounds i8, ptr [[BASE]], i64 8
; CHECK-NEXT:    [[GEP_VAR:%.*]] = getelementptr inbounds float, ptr [[GEP_CONST]], i64 [[IDX]]
; CHECK-NEXT:    [[IDX2:%.*]] = shl i64 [[IDX]], 1
; CHECK-NEXT:    [[GEP_VAR2:%.*]] = getelementptr inbounds float, ptr [[GEP_CONST]], i64 [[IDX2]]
; CHECK-NEXT:    [[LOAD:%.*]] = load float, ptr [[GEP_VAR]], align 4
; CHECK-NEXT:    [[LOAD2:%.*]] = load float, ptr [[GEP_VAR2]], align 8
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "align"(ptr %base, i64 16) ]
  %gep.const = getelementptr inbounds i8, ptr %base, i64 8
  %gep.var = getelementptr inbounds float, ptr %gep.const, i64 %idx
  %idx2 = shl i64 %idx, 1
  %gep.var2 = getelementptr inbounds float, ptr %gep.const, i64 %idx2
  %load = load float, ptr %gep.var, align 4
  %load2 = load float, ptr %gep.var2, align 4
  ret void
}

define void @test_addrspace_cast(ptr %base, i64 %idx) {
; CHECK-LABEL: define void @test_addrspace_cast
; CHECK-SAME: (ptr [[BASE:%.*]], i64 [[IDX:%.*]]) {
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[BASE]], i64 16) ]
; CHECK-NEXT:    [[CAST:%.*]] = addrspacecast ptr [[BASE]] to ptr addrspace(1)
; CHECK-NEXT:    [[IDX8:%.*]] = shl i64 [[IDX]], 1
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds float, ptr addrspace(1) [[CAST]], i64 [[IDX8]]
; CHECK-NEXT:    [[LOAD:%.*]] = load float, ptr addrspace(1) [[GEP]], align 8
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "align"(ptr %base, i64 16) ]
  %cast = addrspacecast ptr %base to ptr addrspace(1)
  %idx8 = shl i64 %idx, 1
  %gep = getelementptr inbounds float, ptr addrspace(1) %cast, i64 %idx8
  %load = load float, ptr addrspace(1) %gep, align 4
  ret void
}

define void @test_multiple_indices_known_bits(ptr %base, i64 %i, i64 %j) {
; CHECK-LABEL: define void @test_multiple_indices_known_bits
; CHECK-SAME: (ptr [[BASE:%.*]], i64 [[I:%.*]], i64 [[J:%.*]]) {
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[BASE]], i64 16) ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [10 x [10 x float]], ptr [[BASE]], i64 [[I]], i64 [[J]]
; CHECK-NEXT:    [[LOAD:%.*]] = load float, ptr [[GEP]], align 8
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "align"(ptr %base, i64 16) ]
  %gep = getelementptr inbounds [10 x [10 x float]], ptr %base, i64 %i, i64 %j
  %load = load float, ptr %gep, align 4
  ret void
}

define void @test_keep_better_alignment(ptr %base, i64 %idx) {
; CHECK-LABEL: define void @test_keep_better_alignment
; CHECK-SAME: (ptr [[BASE:%.*]], i64 [[IDX:%.*]]) {
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[BASE]], i64 4) ]
; CHECK-NEXT:    [[IDX2:%.*]] = shl i64 [[IDX]], 1
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds float, ptr [[BASE]], i64 [[IDX2]]
; CHECK-NEXT:    [[LOAD:%.*]] = load float, ptr [[GEP]], align 16
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "align"(ptr %base, i64 4) ]
  %idx2 = shl i64 %idx, 1
  %gep = getelementptr inbounds float, ptr %base, i64 %idx2
  %load = load float, ptr %gep, align 16
  ret void
}

%struct.S12 = type { i32, i32, i32 }

define void @test_non_pow2_element_size(ptr %base, i64 %idx) {
; CHECK-LABEL: define void @test_non_pow2_element_size
; CHECK-SAME: (ptr [[BASE:%.*]], i64 [[IDX:%.*]]) {
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[BASE]], i64 4) ]
; CHECK-NEXT:    [[IDX_SHIFTED:%.*]] = shl i64 [[IDX]], 1
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [[STRUCT_S12:%.*]], ptr [[BASE]], i64 [[IDX_SHIFTED]]
; CHECK-NEXT:    [[LOAD:%.*]] = load [[STRUCT_S12]], ptr [[GEP]], align 4
; CHECK-NEXT:    ret void
;
  call void @llvm.assume(i1 true) [ "align"(ptr %base, i64 4) ]
  %idx.shifted = shl i64 %idx, 1
  %gep = getelementptr inbounds %struct.S12, ptr %base, i64 %idx.shifted
  %load = load %struct.S12, ptr %gep, align 4
  ret void
}

declare void @llvm.assume(i1)
