; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes=mldst-motion -S < %s | FileCheck %s

define void @no_gep_same_ptr(i1 %c, ptr %p, i32 %x, i32 %y) {
; CHECK-LABEL: define void @no_gep_same_ptr(
; CHECK-SAME: i1 [[C:%.*]], ptr [[P:%.*]], i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[C]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    store i32 [[X]], ptr [[P]], align 4
; CHECK-NEXT:    br label [[IF_END:%.*]]
; CHECK:       if.else:
; CHECK-NEXT:    store i32 [[Y]], ptr [[P]], align 4, !mmra [[META0:![0-9]+]]
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    ret void
;
entry:
  br i1 %c, label %if.then, label %if.else

if.then:
  store i32 %x, ptr %p
  br label %if.end

if.else:
  store i32 %y, ptr %p, !mmra !0
  br label %if.end

if.end:
  ret void
}

!0 = !{!"foo", !"bar"}
;.
; CHECK: [[META0]] = !{!"foo", !"bar"}
;.
